import React, { useState } from 'react';
import { View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { design } from '../theme';
import { api, request } from '../services/api';
import { useSession } from '../context/SessionContext';
import { useResource } from '../hooks/useResource';
import { Button, Card, Input, Label, State } from './ui';
interface RegistrationState { capacity: number | null; confirmedCount: number; waitingCount: number; registration: { status: string } | null }
export function Attendance({ eventId, onLogin }: { eventId: string; onLogin?: () => void }) {
  const session = useSession();
  const r = useResource<RegistrationState>(() => request(`/events/${eventId}/registration`), `attendance:${eventId}`);
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [ticket, setTicket] = useState<{ token: string; expiresAt: number } | null>(null);
  async function perform(task: () => Promise<unknown>) { setBusy(true); setError(null); try { await task(); await r.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível atualizar a inscrição.'); } finally { setBusy(false); } }
  const status = r.data?.registration?.status;
  return <Card><Label bold size={design.type.title}>Sua presença</Label>{r.loading && !r.data ? <State loading /> : r.error ? <State error={r.error} retry={r.reload} /> : <><Label muted>{r.data?.confirmedCount || 0} presenças confirmadas{r.data?.capacity ? ` · ${r.data.capacity} vagas` : ''}</Label><Label>{status === 'WAITLISTED' ? 'Você está na lista de espera.' : status === 'CONFIRMED' ? 'Sua presença está confirmada.' : status === 'CHECKED_IN' ? 'Sua entrada já foi validada.' : 'Participe desta experiência.'}</Label>{!session.user && <><Label muted>Entre na sua conta para confirmar presença e acessar seu ingresso.</Label><Button title="Entrar para confirmar presença" onPress={() => onLogin?.()} disabled={!onLogin} /></>}{session.user && (!status || status === 'CANCELLED') && <Button title="Confirmar presença" busy={busy} onPress={() => void perform(() => api.registerEvent(eventId))} />}{(status === 'CONFIRMED' || status === 'WAITLISTED') && <Button title="Cancelar minha inscrição" secondary busy={busy} onPress={() => void perform(() => api.cancelRegistration(eventId))} />}{status === 'CONFIRMED' && <Button title="Mostrar QR de entrada" busy={busy} onPress={() => void perform(async () => { setTicket(await request(`/events/${eventId}/check-in-token`)); })} />}{ticket && <><View style={{ padding: design.space.sm, backgroundColor: '#FFF', borderRadius: design.radius.md, alignItems: 'center', gap: design.space.md }}><QRCode value={ticket.token} size={220} /></View><Label muted size={design.type.caption}>Válido até {new Date(ticket.expiresAt).toLocaleTimeString('pt-BR')}. Gere novamente se expirar.</Label></>}</>}{error && <Label>{error}</Label>}</Card>;
}
export function EventReport({ eventId }: { eventId: string }) { const [open, setOpen] = useState(false), [details, setDetails] = useState(''), [reason, setReason] = useState('INCORRECT_INFORMATION'), [busy, setBusy] = useState(false), [message, setMessage] = useState(''); async function send() { setBusy(true); try { await api.reportEvent(eventId, reason, details); setMessage('Denúncia registrada. A equipe fará a análise.'); setOpen(false); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Falha ao enviar denúncia.'); } finally { setBusy(false); } } return <Card><Button title={open ? 'Fechar denúncia' : 'Denunciar problema neste evento'} secondary onPress={() => setOpen(v => !v)} />{open && <>{[{ id: 'INCORRECT_INFORMATION', label: 'Informação incorreta' },{ id: 'INAPPROPRIATE_CONTENT', label: 'Conteúdo inadequado' },{ id: 'SPAM', label: 'Spam' },{ id: 'OTHER', label: 'Outro motivo' }].map(v => <Button key={v.id} title={`${reason === v.id ? '✓ ' : ''}${v.label}`} secondary onPress={() => setReason(v.id)} />)}<Input label="Descreva o problema" value={details} onChangeText={setDetails} multiline maxLength={1000} /><Button title="Enviar denúncia" disabled={details.trim().length < 5} busy={busy} onPress={() => void send()} /></>}{Boolean(message) && <Label>{message}</Label>}</Card>; }
