import React, { useState } from 'react';
import { Alert } from 'react-native';
import { api, request } from '../services/api';
import { useResource } from '../hooks/useResource';
import { Button, Card, Input, Label, State } from './ui';
interface History { id: string; action: string; createdAt: string; note?: string | null; actorName?: string | null }
export function EventManagement({ eventId, onDuplicate, onChanged }: { eventId: string; onDuplicate: () => void; onChanged: () => void }) { const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [frequency, setFrequency] = useState<'WEEKLY' | 'MONTHLY'>('WEEKLY'), [count, setCount] = useState('3'), [interval, setInterval] = useState('1'); const h = useResource<History[]>(() => open ? request<{ history: History[] }>(`/events/${encodeURIComponent(eventId)}/history`).then(result => { if (!Array.isArray(result.history)) throw new Error('Não foi possível ler o histórico deste evento.'); return result.history; }) : Promise.resolve([]), `${eventId}:${open}`); async function perform(task: () => Promise<unknown>, success: string) { setBusy(true); setMessage(''); try { await task(); setMessage(success); onChanged(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Não foi possível concluir.'); } finally { setBusy(false); } }
return <Card><Label bold size={18}>Gerenciar evento</Label><Button title="Duplicar como rascunho" secondary busy={busy} onPress={() => void perform(async () => { await api.eventAction(eventId, 'duplicate'); onDuplicate(); }, 'Evento duplicado como rascunho.')} /><Button title="Cancelar evento" secondary busy={busy} onPress={() => Alert.alert('Cancelar evento?', 'Os participantes serão informados do cancelamento.', [{ text: 'Voltar', style: 'cancel' }, { text: 'Cancelar evento', style: 'destructive', onPress: () => void perform(() => api.eventAction(eventId, 'cancel'), 'Evento cancelado.') }])} /><Label bold>Repetir evento</Label><Button title={frequency === 'WEEKLY' ? 'A cada semana' : 'A cada mês'} secondary onPress={() => setFrequency(v => v === 'WEEKLY' ? 'MONTHLY' : 'WEEKLY')} /><Input label="Intervalo entre ocorrências" value={interval} onChangeText={setInterval} keyboardType="number-pad" /><Input label="Quantidade de novas ocorrências" value={count} onChangeText={setCount} keyboardType="number-pad" /><Button title="Criar recorrência" busy={busy} disabled={!Number.isInteger(Number(count)) || !Number.isInteger(Number(interval)) || Number(count) < 2 || Number(count) > 52 || Number(interval) < 1 || Number(interval) > 4} onPress={() => void perform(() => request(`/events/${eventId}/recurrence`, { method: 'POST', body: { frequency, interval: Number(interval), count: Number(count) } }), 'Ocorrências criadas.')} /><Button title={open ? 'Ocultar histórico' : 'Histórico de alterações'} secondary onPress={() => setOpen(v => !v)} />{open && (h.loading || h.error ? <State loading={h.loading} error={h.error} retry={h.reload} /> : h.data?.map(v => <Card key={v.id}><Label bold>{v.action}</Label><Label muted size={12}>{new Date(v.createdAt).toLocaleString('pt-BR')} · {v.actorName || 'Equipe'}</Label>{v.note && <Label>{v.note}</Label>}</Card>))}{Boolean(message) && <Label>{message}</Label>}</Card>;
}

