import React, { useState, type ReactNode } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View, type TextInputProps } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useTheme } from '../theme';
export function Label({ children, muted = false, size = 15, bold = false }: { children: ReactNode; muted?: boolean; size?: number; bold?: boolean }) { const t = useTheme(); return <Text style={{ color: muted ? t.muted : t.text, fontFamily: bold ? 'GeistBold' : 'Geist', fontSize: size, fontWeight: bold ? '700' : '400', lineHeight: size * 1.45 }}>{children}</Text>; }
export function Card({ children }: { children: ReactNode }) { const t = useTheme(); return <View style={{ backgroundColor: t.surface, borderColor: t.border, borderWidth: 1, borderRadius: 22, padding: 18, gap: 12 }}>{children}</View>; }
export function Button({ title, onPress, secondary = false, disabled = false, busy = false }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; busy?: boolean }) { const t = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{ disabled: disabled || busy, busy }} disabled={disabled || busy} onPress={onPress} style={({ pressed }) => ({ minHeight: 48, borderRadius: 14, backgroundColor: secondary ? t.soft : t.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 12, opacity: disabled || busy ? 0.5 : pressed ? 0.75 : 1 })}>{busy ? <ActivityIndicator color={secondary ? t.primary : '#FFF'} /> : <Text style={{ fontFamily: 'GeistSemiBold', fontSize: 15, fontWeight: '600', textAlign: 'center', color: secondary ? t.primary : t.background === '#080808' ? '#080808' : '#FFF' }}>{title}</Text>}</Pressable>; }
export function Input({ label, ...props }: TextInputProps & { label: string }) { const t = useTheme(); const [focused, setFocused] = useState(false); return <View style={{ gap: 7 }}><Label size={13} bold>{label}</Label><TextInput accessibilityLabel={label} placeholderTextColor={t.muted} {...props} onFocus={event => { setFocused(true); props.onFocus?.(event); }} onBlur={event => { setFocused(false); props.onBlur?.(event); }} style={[{ color: t.text, backgroundColor: t.surface, borderWidth: 1, borderColor: focused ? t.primary : t.border, padding: 14, borderRadius: 14, minHeight: 48, fontFamily: 'Geist', fontSize: 16, textAlignVertical: props.multiline ? 'top' : 'center' }, props.style]} /></View>; }
export function Avatar({ name, uri }: { name: string; uri?: string | null }) { const t = useTheme(); const [failedUri, setFailedUri] = useState<string | null>(null); return uri && failedUri !== uri ? <Image onError={() => setFailedUri(uri)} accessibilityLabel={name} source={{ uri }} style={{ width: 52, height: 52, borderRadius: 26 }} /> : <View style={{ width: 52, height: 52, borderRadius: 26, backgroundColor: t.soft, alignItems: 'center', justifyContent: 'center' }}><Label size={20} bold>{name.slice(0, 1).toUpperCase()}</Label></View>; }
export function Screen({ title, subtitle, children, onBack, action }: { title: string; subtitle?: string; children: ReactNode; onBack?: () => void; action?: ReactNode }) { const t = useTheme(); const insets = useSafeAreaInsets(); return <SafeAreaView style={{ flex: 1, backgroundColor: t.background }} edges={['top', 'left', 'right']}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 20, paddingBottom: Math.max(40, insets.bottom + 24), gap: 20, maxWidth: 760, width: '100%', alignSelf: 'center' }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>{onBack && <Pressable accessibilityRole="button" accessibilityLabel="Voltar" onPress={onBack} style={{ padding: 12, backgroundColor: t.surface, borderRadius: 14 }}><Label size={22}>‹</Label></Pressable>}<View style={{ flex: 1 }}><Label size={28} bold>{title}</Label>{Boolean(subtitle) && <Label muted size={13}>{subtitle}</Label>}</View>{action}</View>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>; }
export function State({ loading, error, retry, empty }: { loading?: boolean; error?: string | null; retry?: () => void; empty?: string }) { const t = useTheme(); if (loading) return <View accessibilityLabel="Carregando" accessibilityState={{ busy: true }} style={{ padding: 30 }}><ActivityIndicator color={t.primary} /></View>; return <Card><Label muted>{error || empty || 'Nenhum resultado por aqui ainda.'}</Label>{error && retry && <Button title="Tentar novamente" secondary onPress={retry} />}</Card>; }



