"use client";

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Mic, Paperclip, Send, Smile } from "lucide-react";
import styles from "./Chat.module.css";

const emojis = ["😀", "😊", "😂", "🥰", "❤️", "🔥", "🎉", "🙌", "👍", "✨", "🎶", "👋"];
export function MessageInput({ value, onChange, onBlur, onSubmit, disabled, hasAttachment, attach, children, uploading }: { value: string; onChange: (value: string) => void; onBlur: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean; hasAttachment: boolean; attach?: () => void; children?: ReactNode; uploading: boolean }) {
  const input = useRef<HTMLTextAreaElement>(null), composing = useRef(false);
  const [emojiOpen, setEmojiOpen] = useState(false), [audioNotice, setAudioNotice] = useState(false);
  useEffect(() => { const element = input.current; if (element) { element.style.height = "auto"; element.style.height = `${Math.min(element.scrollHeight, 120)}px`; } }, [value]);
  useEffect(() => { input.current?.focus({ preventScroll: true }); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { onSubmit(event); input.current?.focus({ preventScroll: true }); };
  return <form className={styles.composer} onSubmit={submit}>{children}{emojiOpen && <div className={styles.emojiPanel} aria-label="Escolher emoji">{emojis.map(emoji => <button key={emoji} type="button" aria-label={`Inserir ${emoji}`} onClick={() => { onChange(value + emoji); setEmojiOpen(false); input.current?.focus(); }}>{emoji}</button>)}</div>}{audioNotice && <p role="status" className={styles.notice}>Mensagens de voz ainda não estão disponíveis. Envie texto ou uma foto.</p>}<div className={styles.inputRow}><button type="button" className={styles.iconButton} aria-label="Escolher emoji" aria-expanded={emojiOpen} onClick={() => setEmojiOpen(open => !open)}><Smile size={24} /></button>{attach && <button type="button" className={styles.iconButton} aria-label="Anexar foto" disabled={disabled} onClick={attach}><Paperclip size={23} /></button>}<label className="sr-only" htmlFor="event-chat-message">Sua mensagem</label><textarea ref={input} id="event-chat-message" value={value} rows={1} maxLength={1000} placeholder="Escreva uma mensagem" aria-describedby="event-chat-hint" onChange={event => onChange(event.target.value)} onBlur={onBlur} onCompositionStart={() => { composing.current = true; }} onCompositionEnd={() => { composing.current = false; }} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing && !composing.current && event.keyCode !== 229) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} />{value.trim() || hasAttachment || uploading ? <button type="submit" className={styles.sendButton} disabled={disabled || (!value.trim() && !hasAttachment)} aria-label={uploading ? "Enviando foto…" : "Enviar mensagem"}><Send size={22} /><span className="sr-only">{uploading ? "Enviando foto…" : "Enviar mensagem"}</span></button> : <button type="button" className={styles.iconButton} aria-label="Mensagens de voz: ver disponibilidade" onClick={() => setAudioNotice(open => !open)}><Mic size={24} /></button>}</div><p id="event-chat-hint" className={styles.inputHint}>{value.length}/1000 · Enter envia · Shift+Enter quebra a linha</p></form>;
}
