"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, BellRing, CalendarDays, CheckCheck, ClipboardCheck, Compass, RefreshCw, Search, Sparkles, Ticket, UsersRound, X } from "lucide-react";
import type { ActivitySnapshot } from "@/types/activity";
import { useActivityRealtime } from "@/hooks/useActivityRealtime";
import { useActivityActions } from "@/hooks/useActivityActions";
import { useCommunityResource } from "./CommunityResource";
import { CommunitySyncStatus } from "./CommunityUI";
import { ActivityCard, ActivitySection } from "./ActivityDashboardCards";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { FadeInView } from "@/components/animations/FadeInView";

type Filter = "all" | "queues" | "tasks" | "registrations" | "rooms";
type PendingAction = { identity: string; eventId: string; id: string; title: string; action: "queue.leave" | "task.update"; status?: "DONE" };
const filters: { id: Filter; label: string }[] = [{ id: "all", label: "Tudo" }, { id: "queues", label: "Filas" }, { id: "tasks", label: "Tarefas" }, { id: "registrations", label: "Próximos eventos" }, { id: "rooms", label: "Com amigos" }];
const communityHref = (id: string) => `/eventos/${encodeURIComponent(id)}/comunidade`;
const dateLabel = (value: string) => {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Horário a confirmar" : new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(date);
};

export function ActivityDashboard() {
  const resource = useCommunityResource<ActivitySnapshot>("/api/community/activity");
  const actions = useActivityActions(resource.identity, resource.refresh);
  const [pending, setPending] = useState<PendingAction | null>(null);
  const actionTrigger = useRef<HTMLElement | null>(null);
  const realtime = useActivityRealtime({ eventIds: [...(resource.data?.queues ?? []), ...(resource.data?.tasks ?? []), ...(resource.data?.registrations ?? [])].map(item => item.eventId), roomIds: (resource.data?.rooms ?? []).map(item => item.id) }, resource.refresh);
  const [filter, setFilter] = useState<Filter>("all");
  const [search, setSearch] = useState("");
  const data = resource.data;
  const pendingAvailable = pending?.identity === resource.identity && resource.authenticated && !!data && (pending.action === "queue.leave" ? data.queues : data.tasks).some(item => item.id === pending.id && item.eventId === pending.eventId);
  useEffect(() => {
    if (!pendingAvailable) setPending(null);
  }, [pendingAvailable]);
  const disabledActions = actions.busy || !resource.online || !resource.authenticated;
  const askConfirmation = (item: { eventId: string; id: string; title: string }, action: PendingAction["action"]) => {
    actionTrigger.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    actions.clearFeedback();
    setPending({ ...item, identity: resource.identity, action, ...(action === "task.update" ? { status: "DONE" as const } : {}) });
  };
  const confirmAction = async () => {
    if (!pending || !pendingAvailable || disabledActions) return;
    const completed = await actions.run({ eventId: pending.eventId, id: pending.id, action: pending.action, ...(pending.status ? { status: pending.status } : {}) });
    if (completed) setPending(null);
  };
  const matches = (...values: string[]) => values.join(" ").toLocaleLowerCase("pt-BR").includes(search.trim().toLocaleLowerCase("pt-BR"));
  const queues = (data?.queues ?? []).filter(item => matches(item.title, item.eventName)).slice().sort((left, right) => Number(right.status === "CALLED" && right.state !== "CLOSED") - Number(left.status === "CALLED" && left.state !== "CLOSED"));
  const tasks = (data?.tasks ?? []).filter(item => matches(item.title, item.eventName));
  const registrations = (data?.registrations ?? []).filter(item => matches(item.eventName));
  const rooms = (data?.rooms ?? []).filter(item => matches(item.name));
  const selectedCount = filter === "all" ? queues.length + tasks.length + registrations.length + rooms.length : { queues: queues.length, tasks: tasks.length, registrations: registrations.length, rooms: rooms.length }[filter];
  const called = (data?.queues ?? []).filter(item => item.status === "CALLED" && item.state !== "CLOSED");
  const show = (id: Filter) => filter === "all" || filter === id;

  return <main className="min-w-0 w-full px-4 py-6 sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl space-y-8">
    <header className="relative isolate overflow-hidden rounded-[28px] border border-border bg-card shadow-surface p-6 sm:p-8 lg:p-10">
      <div aria-hidden="true" className="pointer-events-none absolute -right-14 -top-20 -z-10 size-72 rounded-full border-[32px] border-border sm:size-96" />
      <div className="flex flex-wrap items-start justify-between gap-6"><FadeInView className="max-w-2xl"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-primary"><Sparkles className="size-4" aria-hidden="true" /> Sua experiência, organizada</p><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">Central de atividades</h1><p className="mt-4 max-w-xl text-sm leading-7 text-muted-foreground sm:text-base">Acompanhe o que precisa da sua atenção e prepare o próximo encontro. Suas filas, compromissos e amigos, em um só lugar.</p></FadeInView><Link href="/EventsCreated" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground shadow-highlight transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><Compass className="size-4" aria-hidden="true" /> Descobrir eventos <ArrowRight className="size-4" aria-hidden="true" /></Link></div>
      <div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">
        {[{ id: "queues" as const, icon: Ticket, label: "Seus atendimentos", value: data?.counts.queues }, { id: "tasks" as const, icon: ClipboardCheck, label: "Tarefas pendentes", value: data?.counts.tasks }, { id: "registrations" as const, icon: CalendarDays, label: "Próximas inscrições", value: data?.counts.registrations }, { id: "rooms" as const, icon: UsersRound, label: "Salas com amigos", value: data?.counts.rooms }].map(({ id, icon: Icon, label, value }) => <button key={id} type="button" disabled={!data} aria-pressed={filter === id} onClick={() => setFilter(filter === id ? "all" : id)} className={`min-w-0 rounded-2xl border bg-muted p-4 text-left transition hover:border-primary/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default ${filter === id ? "border-primary/40" : "border-border"}`}><span className="flex items-center gap-2 text-primary"><Icon className="size-4 shrink-0" aria-hidden="true" /><span className="text-xs font-medium text-muted-foreground">{label}</span></span><span className="mt-3 block text-3xl font-semibold tracking-tight">{value ?? "—"}</span></button>)}
      </div>
      <p className="mt-3 text-xs text-muted-foreground">Resumo dos itens exibidos nesta central.</p>
    </header>

    <div className="flex flex-wrap items-center justify-between gap-3"><CommunitySyncStatus realtime={realtime} refreshing={resource.refreshing} error={resource.error} lastSuccessfulAt={resource.lastSuccessfulAt} /><Button type="button" variant="outline" disabled={resource.refreshing || !resource.online} onClick={() => void resource.refresh()} className="min-h-11 rounded-xl"><RefreshCw className="size-4" aria-hidden="true" />{resource.refreshing ? "Atualizando..." : "Atualizar"}</Button></div>
    <p className="text-xs leading-5 text-muted-foreground">Até 12 eventos e 6 salas recebem atualizações ao vivo. A central também confere suas atividades a cada 30 segundos enquanto esta página está visível e conectada.</p>
    {(!resource.online || resource.error) && <aside role="alert" className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm leading-6"><p>{!resource.online ? "Você está sem conexão. Os últimos dados recebidos continuam disponíveis para consulta." : resource.error}</p>{data && <p className="mt-1 text-muted-foreground">Algumas atividades podem ter mudado. Atualize quando a conexão estiver disponível.</p>}</aside>}
    {(actions.error || actions.message) && <aside role={actions.error ? "alert" : "status"} className={`flex items-start justify-between gap-3 rounded-2xl border p-4 text-sm leading-6 ${actions.error ? "border-amber-500/30 bg-amber-500/10" : "border-emerald-500/30 bg-emerald-500/10"}`}><p>{actions.error || actions.message}</p><button type="button" onClick={actions.clearFeedback} aria-label="Fechar aviso" className="grid size-9 shrink-0 place-items-center rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><X className="size-4" aria-hidden="true" /></button></aside>}

    {!resource.authenticated && !resource.loading ? <section className="rounded-2xl border bg-card p-8 text-center"><h2 className="text-xl font-semibold">Suas atividades pertencem à sua conta</h2><p className="mt-2 text-sm text-muted-foreground">Entre para acompanhar seus eventos, filas e salas.</p><Link href="/login" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground">Entrar na plataforma</Link></section> : resource.loading ? <div role="status" className="space-y-4"><p className="text-sm text-muted-foreground">Organizando suas atividades...</p><div aria-hidden="true" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map(id => <div key={id} className="h-48 rounded-2xl border bg-muted/50" />)}</div></div> : data && <>
      {called.length > 0 && <aside aria-labelledby="called-heading" className="rounded-2xl border border-primary/30 bg-primary/5 p-5"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><BellRing className="size-5" aria-hidden="true" /></span><div className="min-w-0"><h2 id="called-heading" className="font-semibold">Chegou sua vez!</h2><p className="mt-1 text-sm text-muted-foreground">Você foi chamado em {called.length === 1 ? "uma fila. Confira o atendimento abaixo." : `${called.length} filas. Confira os atendimentos abaixo.`}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{called.map(item => <Link key={item.id} href={communityHref(item.eventId)} className="inline-flex min-h-11 max-w-full items-center gap-2 rounded-xl border bg-background px-4 py-2 text-sm font-semibold text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="break-words">{item.title} · {item.eventName}</span><ArrowRight className="size-4 shrink-0" aria-hidden="true" /></Link>)}</div></aside>}

      <section aria-label="Filtrar atividades" className="space-y-4 rounded-2xl border bg-card p-4 sm:p-5"><label htmlFor="activity-search" className="sr-only">Buscar nas suas atividades</label><div className="relative"><Search className="pointer-events-none absolute left-3.5 top-3.5 size-4 text-muted-foreground" aria-hidden="true" /><input id="activity-search" type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar evento, tarefa ou sala..." className="min-h-11 w-full min-w-0 rounded-xl border bg-background pl-10 pr-11 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" />{search && <button type="button" aria-label="Limpar busca" onClick={() => setSearch("")} className="absolute right-0 top-0 grid size-11 place-items-center rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><X className="size-4" /></button>}</div><div className="flex flex-wrap gap-2" aria-label="Categorias">{filters.map(item => <button key={item.id} type="button" aria-pressed={filter === item.id} onClick={() => setFilter(item.id)} className={`min-h-11 rounded-xl px-4 text-sm font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${filter === item.id ? "bg-primary text-primary-foreground" : "bg-muted/60 text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{item.label}</button>)}</div></section>

      <p role="status" aria-live="polite" className="text-sm text-muted-foreground">{selectedCount} {selectedCount === 1 ? "atividade encontrada" : "atividades encontradas"}{search.trim() ? ` para “${search.trim()}”` : ""}</p>
      {selectedCount === 0 && <section className="rounded-2xl border border-dashed bg-card px-6 py-10 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary/10 text-primary"><CheckCheck className="size-7" aria-hidden="true" /></span><h2 className="mt-4 text-xl font-semibold">{search || filter !== "all" ? "Nenhuma atividade neste filtro" : "Tudo tranquilo por aqui"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{search || filter !== "all" ? "Experimente outra busca ou veja todas as categorias." : "Suas próximas inscrições, filas e tarefas aparecerão aqui. Que tal combinar um evento com seus amigos?"}</p><Button asChild variant="outline" className="mt-5 min-h-11 rounded-xl"><Link href="/salas">Explorar minhas salas <ArrowRight className="size-4" /></Link></Button>{(search || filter !== "all") && <Button type="button" variant="ghost" className="mt-5 min-h-11 rounded-xl" onClick={() => { setSearch(""); setFilter("all"); }}>Limpar filtros</Button>}</section>}

      {show("queues") && queues.length > 0 && <ActivitySection id="queues" title="Seus atendimentos" description="Acompanhe sua vez sem perder de vista o evento." count={queues.length} truncated={data.truncated.queues}>{queues.map(item => <ActivityCard key={item.id} icon={Ticket} title={item.title} eyebrow={item.eventName} urgent={item.status === "CALLED" && item.state !== "CLOSED"} href={communityHref(item.eventId)} action="Ver atendimento" quickActions={<Button type="button" variant="outline" className="min-h-11 rounded-xl" disabled={disabledActions} onClick={() => askConfirmation(item, "queue.leave")}>Sair da fila</Button>}><p className="font-semibold text-foreground">{item.state === "CLOSED" ? "Fila encerrada" : item.status === "CALLED" ? "Sua vez · procure a equipe" : item.position > 0 ? `Você está na posição ${item.position}` : "Aguardando atendimento"}</p><p>{item.state === "PAUSED" ? "Novas entradas estão pausadas." : item.state === "CLOSED" ? "Confira as orientações na comunidade do evento." : "A posição acompanha as atualizações da equipe."}</p></ActivityCard>)}</ActivitySection>}
      {show("tasks") && tasks.length > 0 && <ActivitySection id="tasks" title="Sua parte no evento" description="Tarefas atribuídas a você pela equipe organizadora." count={tasks.length} truncated={data.truncated.tasks}>{tasks.map(item => <ActivityCard key={item.id} icon={ClipboardCheck} title={item.title} eyebrow={item.eventName} href={communityHref(item.eventId)} action="Abrir tarefa" quickActions={<><Button type="button" className="min-h-11 rounded-xl" disabled={disabledActions} onClick={() => askConfirmation(item, "task.update")}>Concluir tarefa</Button>{item.status === "TODO" && <Button type="button" variant="outline" className="min-h-11 rounded-xl" disabled={disabledActions} onClick={() => { actions.clearFeedback(); void actions.run({ eventId: item.eventId, id: item.id, action: "task.update", status: "HELP" }); }}>Pedir ajuda</Button>}</>}><span className="inline-flex rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{item.status === "HELP" ? "Ajuda solicitada" : "A fazer"}</span><p>{item.status === "HELP" ? "Você pediu apoio. Acompanhe a tarefa junto da equipe." : "Veja os detalhes e atualize o andamento na comunidade."}</p></ActivityCard>)}</ActivitySection>}
      {show("registrations") && registrations.length > 0 && <ActivitySection id="registrations" title="Na sua programação" description="Inscrições confirmadas em eventos próximos ou em andamento." count={registrations.length} truncated={data.truncated.registrations}>{registrations.map(item => <ActivityCard key={item.id} icon={CalendarDays} title={item.eventName} eyebrow={dateLabel(item.startsAt)} href={`/eventos/${encodeURIComponent(item.eventId)}`} action="Ver evento e entrada"><span className="inline-flex rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-700 dark:text-emerald-400">{item.status === "CHECKED_IN" ? "Entrada realizada" : "Inscrição confirmada"}</span><p>Confira o local, sua entrada e a comunidade do evento.</p></ActivityCard>)}</ActivitySection>}
      {show("rooms") && rooms.length > 0 && <ActivitySection id="rooms" title="Combinar com amigos" description="Um espaço para escolher experiências com a sua turma." count={rooms.length} truncated={data.truncated.rooms}>{rooms.map(item => <ActivityCard key={item.id} icon={UsersRound} title={item.name} eyebrow="Sua turma" href={`/salas/${encodeURIComponent(item.id)}`} action="Entrar na sala"><p><span className="font-semibold text-foreground">{item.members}</span> {item.members === 1 ? "pessoa" : "pessoas"} · <span className="font-semibold text-foreground">{item.suggestions}</span> {item.suggestions === 1 ? "sugestão" : "sugestões"}</p><p>Sugira eventos e vote no próximo encontro.</p></ActivityCard>)}</ActivitySection>}
    </>}
    <Dialog open={!!pending && pendingAvailable} onOpenChange={open => { if (!open) setPending(null); }}>
      <DialogContent className="max-h-[85dvh] w-[calc(100%-2rem)] overflow-y-auto rounded-2xl sm:rounded-2xl" onCloseAutoFocus={event => { if (actionTrigger.current?.isConnected) { event.preventDefault(); actionTrigger.current.focus(); } }}>
        <DialogHeader><DialogTitle>{pending?.action === "queue.leave" ? "Sair deste atendimento?" : "Concluir esta tarefa?"}</DialogTitle><DialogDescription className="break-words leading-6"><span className="block font-medium text-foreground">{pending?.title}</span>{pending?.action === "queue.leave" ? "Sua posição será perdida. Se entrar novamente, você irá para o fim da fila. Uma fila pausada ou encerrada pode não permitir uma nova entrada." : "A tarefa será marcada como concluída e a equipe verá a atualização. Ela deixará de aparecer entre suas pendências."}</DialogDescription></DialogHeader>
        {!resource.online && <p role="status" className="text-sm text-muted-foreground">Reconecte-se para confirmar esta ação.</p>}
        {actions.error && <p role="alert" className="text-sm leading-6 text-amber-700 dark:text-amber-400">{actions.error}</p>}
        <DialogFooter className="gap-2"><Button type="button" variant="outline" className="min-h-11 rounded-xl" onClick={() => setPending(null)}>Cancelar</Button><Button type="button" variant={pending?.action === "queue.leave" ? "destructive" : "default"} className="min-h-11 rounded-xl" disabled={disabledActions} onClick={() => void confirmAction()}>{actions.busy ? "Salvando..." : pending?.action === "queue.leave" ? "Confirmar saída" : "Confirmar conclusão"}</Button></DialogFooter>
      </DialogContent>
    </Dialog>
  </div></main>;
}
