import React, { useEffect, useRef, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../services/api';
import { Button, Card, Label } from '../ui';
type Reason = 'HARASSMENT' | 'SPAM' | 'SAFETY' | 'OTHER';
const reasons: { value: Reason; label: string }[] = [{ value: 'HARASSMENT', label: 'Assédio' },{ value: 'SPAM', label: 'Spam' },{ value: 'SAFETY', label: 'Risco à segurança' },{ value: 'OTHER', label: 'Outro motivo' }];
interface Props { eventId: string; userId: string; displayName: string; messageId?: number; evidence?: string; label?: string; onBlocked?: () => void; onChanged?: () => void }
export function PartySafetyMenu({ eventId, userId, displayName, messageId, evidence, label = 'Segurança e denúncia', onBlocked, onChanged }: Props) {
  const [open, setOpen] = useState(false), [reason, setReason] = useState<Reason>('SAFETY'), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null);
  const active = useRef(true); useEffect(() => { active.current = true; return () => { active.current = false; }; }, []);
  async function report() { if (!active.current) return; setBusy(true); setError(null); setNotice(null); try { await api.partyAction(eventId, { action: 'report', userId, reason, ...(messageId ? { messageId } : {}) }); if (!active.current) return; setNotice('Denúncia registrada. A equipe analisará o caso.'); onChanged?.(); } catch (cause) { if (!active.current) return; setError(cause instanceof Error ? cause.message : 'Não foi possível enviar a denúncia.'); } finally { if (active.current) setBusy(false); } }
  async function block() { if (!active.current) return; setBusy(true); setError(null); try { await api.partyAction(eventId, { action: 'block', userId }); if (!active.current) return; setOpen(false); onChanged?.(); onBlocked?.(); } catch (cause) { if (!active.current) return; setError(cause instanceof Error ? cause.message : 'Não foi possível bloquear a pessoa.'); } finally { if (active.current) setBusy(false); } }
  return <><Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${displayName}`} onPress={() => { setNotice(null); setError(null); setOpen(true); }} style={{ minHeight: 44, justifyContent: 'center', paddingVertical: 10 }}><Label size={12} muted>{label}</Label></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => { if (!busy) setOpen(false); }}><SafeAreaView style={{ flex: 1, backgroundColor: '#00000088', justifyContent: 'center', padding: 20 }}><ScrollView contentContainerStyle={{ flexGrow: 1, justifyContent: 'center' }}><Card><View style={{ gap: 8 }}><Label bold size={21}>Segurança · {displayName}</Label>{messageId && <><Label muted size={12}>Esta denúncia inclui a mensagem selecionada como evidência.</Label><Label>{evidence || 'Mensagem com imagem'}</Label></>}<Label bold size={14}>Motivo da denúncia</Label>{reasons.map(option => <Button key={option.value} title={`${reason === option.value ? '✓ ' : ''}${option.label}`} secondary disabled={busy} onPress={() => setReason(option.value)} />)}{error && <Label>{error}</Label>}{notice && <Label>{notice}</Label>}<Button title="Enviar denúncia" busy={busy} disabled={Boolean(notice)} onPress={() => void report()} /><Button title="Bloquear pessoa e encerrar conexão" secondary disabled={busy} onPress={() => Alert.alert('Bloquear esta pessoa?', 'O bloqueio encerra as conexões entre vocês. Você poderá desbloquear pelas conexões do evento.', [{ text: 'Voltar', style: 'cancel' }, { text: 'Bloquear', style: 'destructive', onPress: () => void block() }])} /><Button title="Fechar" secondary disabled={busy} onPress={() => setOpen(false)} /></View></Card></ScrollView></SafeAreaView></Modal></>;
}


