import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers";

import { SidebarProvider } from "@/components/ui/sidebar"; // Certifique-se que este import existe
import { AppSidebar } from "@/components/ui/app-sidebar";
import GoogleMapsLoader from "@/components/MyComponents/GoogleMapsLoader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <SidebarProvider defaultOpen={defaultOpen}>
          <div className="flex w-full h-screen">
            {/* Sidebar */}
            <AppSidebar />

            {/* Conteúdo Principal */}
            <main className="flex-1 overflow-auto">
              {/* Carregamento global do Google Maps */}
              <GoogleMapsLoader>
                {children}
              </GoogleMapsLoader>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
