"use client";

import type { CommunityEventSnapshot } from "@/types/community";
import { CommunityAction, CommunityBadge, CommunityCard, CommunityEmpty, CommunityField, CommunityForm, CommunitySelect, useCommunityInteractions } from "./CommunityUI";

type SectionProps = { data: CommunityEventSnapshot; busy: boolean; act: (payload: Record<string, unknown>) => Promise<boolean>; userId?: string };
const stringValue = (values: FormData, name: string) => String(values.get(name) ?? "").trim();
function localDateTime(value: string): string { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
const states = { UPCOMING: "A seguir", LIVE: "Acontecendo agora", DONE: "Concluída", TODO: "Pendente", HELP: "Preciso de ajuda" };

export function CommunityAnnouncements({ data, busy, act }: SectionProps) {
  return <CommunityCard title="Comunicados oficiais" description="Acompanhe as orientações e mudanças publicadas pela organização do evento.">
    {data.permissions.manage && <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Publicar comunicado</summary><div className="mt-3"><CommunityForm submit="Publicar comunicado" busy={busy} onSubmit={values => act({ action: "announcement.publish", title: stringValue(values, "title"), message: stringValue(values, "message") })}><CommunityField name="title" label="Título do aviso" maxLength={160} placeholder="Ex.: Mudança na entrada do evento" /><CommunityField name="message" label="Orientação para os participantes" type="textarea" maxLength={1000} /></CommunityForm></div></details>}
    {data.announcements.length ? data.announcements.map(announcement => <article key={announcement.id} className={`space-y-3 rounded-xl border p-4 ${announcement.archived ? "bg-muted/30" : "border-primary/20 bg-primary/5"}`}><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="break-words font-semibold">{announcement.title}</h3><CommunityBadge>{announcement.archived ? "Arquivado" : "Comunicado oficial"}</CommunityBadge></div><p className="whitespace-pre-wrap break-words text-sm leading-6">{announcement.message}</p><time dateTime={announcement.createdAt} className="block text-xs text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(announcement.createdAt))}</time>{data.permissions.manage && !announcement.archived && <CommunityAction busy={busy} onClick={() => { if (window.confirm("Arquivar este comunicado? Ele deixará de aparecer para os participantes.")) void act({ action: "announcement.archive", id: announcement.id }); }}>Arquivar comunicado</CommunityAction>}</article>) : <CommunityEmpty>A organização ainda não publicou comunicados. Confira também a programação e as respostas às perguntas.</CommunityEmpty>}
  </CommunityCard>;
}

export function CommunityQuestions({ data, busy, act }: SectionProps) {
  return <CommunityCard title="Converse com o organizador" description="Pergunte antes de sair de casa. As respostas ficam disponíveis para todos.">
    {data.permissions.authenticated && <CommunityForm submit="Enviar pergunta" busy={busy} onSubmit={values => act({ action: "question.ask", text: stringValue(values, "text") })}><CommunityField name="text" label="Sua dúvida" type="textarea" maxLength={1000} placeholder="Ex.: Onde fica a entrada acessível?" /></CommunityForm>}
    {data.questions.length ? [...data.questions].sort((left, right) => Number(right.highlighted) - Number(left.highlighted)).map(question => <article key={question.id} className="space-y-3 rounded-xl border p-4">{question.highlighted && <CommunityBadge>Resposta em destaque</CommunityBadge>}<h3 className="whitespace-pre-wrap break-words font-semibold">{question.text}</h3>{question.answer ? <div className="rounded-xl bg-primary/5 p-3"><p className="text-xs font-semibold text-primary">Resposta da organização</p><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6">{question.answer}</p></div> : <p className="text-sm text-muted-foreground">Aguardando resposta do organizador.</p>}{data.permissions.team && <details className="rounded-xl bg-muted/40 p-3"><summary className="cursor-pointer text-sm font-semibold">{question.answer ? "Editar resposta" : "Responder"}</summary><div className="mt-3"><CommunityForm submit="Publicar resposta" busy={busy} onSubmit={values => act({ action: "question.answer", id: question.id, answer: stringValue(values, "answer"), highlighted: values.get("highlighted") === "on" })} reset={false}><CommunityField name="answer" label="Resposta" type="textarea" maxLength={1000} defaultValue={question.answer} /><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="highlighted" defaultChecked={question.highlighted} className="size-4 accent-primary" />Destacar como dúvida frequente</label></CommunityForm></div></details>}</article>) : <CommunityEmpty>A conversa começa com sua primeira pergunta.</CommunityEmpty>}
  </CommunityCard>;
}

export function CommunityPolls({ data, busy, act }: SectionProps) {
  const online = useCommunityInteractions();
  return <CommunityCard title="Sua opinião conta" description="Vote em uma opção por enquete e acompanhe o resultado ao vivo.">
    {data.permissions.manage && <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Criar enquete</summary><div className="mt-3"><CommunityForm submit="Publicar enquete" busy={busy} onSubmit={values => { const options = stringValue(values, "options").split("\n").map(value => value.trim()).filter(Boolean); if (options.length < 2 || options.length > 8 || options.some(option => option.length > 120) || new Set(options).size !== options.length) throw new Error("Use de 2 a 8 opções diferentes, com até 120 caracteres cada."); return act({ action: "poll.create", title: stringValue(values, "title"), options }); }}><CommunityField name="title" label="Pergunta da enquete" maxLength={160} /><CommunityField name="options" label="Opções (uma por linha, de 2 a 8, até 120 caracteres cada)" type="textarea" maxLength={2000} placeholder={"Oficina pela manhã\nOficina à tarde"} /></CommunityForm></div></details>}
    {data.polls.length ? data.polls.map(poll => { const total = poll.counts.reduce((sum, count) => sum + count, 0); return <article key={poll.id} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="break-words font-semibold">{poll.title}</h3><CommunityBadge>{poll.closed ? "Encerrada" : "Aberta"}</CommunityBadge></div><div className="space-y-2">{poll.options.map((option, index) => { const count = poll.counts[index] ?? 0; const percentage = total ? Math.round(count * 100 / total) : 0; return <button key={index} type="button" disabled={busy || !online || poll.closed || poll.mine !== null || !data.permissions.authenticated} onClick={() => void act({ action: "poll.vote", id: poll.id, option: index })} aria-pressed={poll.mine === index} className={`relative min-h-12 w-full overflow-hidden rounded-xl border p-3 text-left text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default ${poll.mine === index ? "border-primary" : "hover:border-primary/40"}`}><span className="absolute inset-y-0 left-0 bg-primary/10" style={{ width: `${percentage}%` }} aria-hidden="true" /><span className="relative flex items-start justify-between gap-3"><span className="break-words">{poll.mine === index ? "✓ " : ""}{option}</span><span className="shrink-0 text-xs">{count} · {percentage}%</span></span></button>; })}</div><p className="text-xs text-muted-foreground">{total} votos{poll.mine !== null ? " · Seu voto foi registrado." : ""}</p>{data.permissions.manage && !poll.closed && <CommunityAction busy={busy} onClick={() => { if (window.confirm("Encerrar esta enquete?")) void act({ action: "poll.close", id: poll.id }); }}>Encerrar enquete</CommunityAction>}</article>; }) : <CommunityEmpty>A organização ainda não publicou enquetes.</CommunityEmpty>}
  </CommunityCard>;
}

export function CommunityProgram({ data, busy, act }: SectionProps) {
  return <CommunityCard title="Não perca o próximo momento" description="Confira a programação e acompanhe quais atividades já começaram.">
    {data.permissions.manage && <CommunityForm submit="Adicionar atividade" busy={busy} onSubmit={values => { const date = new Date(stringValue(values, "startsAt")); if (Number.isNaN(date.getTime())) throw new Error("Informe uma data e um horário válidos."); return act({ action: "program.save", title: stringValue(values, "title"), startsAt: date.toISOString() }); }}><div className="grid gap-3 sm:grid-cols-2"><CommunityField name="title" label="Atividade" maxLength={160} /><CommunityField name="startsAt" label="Início (no fuso do seu dispositivo)" type="datetime-local" /></div></CommunityForm>}
    {data.program.length ? <ol className="space-y-3">{data.program.map(activity => <li key={activity.id} className="rounded-xl border-l-4 border border-l-primary/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(activity.startsAt))}</p><h3 className="mt-1 break-words font-semibold">{activity.title}</h3></div><CommunityBadge>{states[activity.status]}</CommunityBadge></div>{data.permissions.manage && <details className="mt-3 rounded-xl bg-muted/40 p-3"><summary className="cursor-pointer text-sm font-semibold">Editar atividade e horário</summary><div className="mt-3"><CommunityForm submit="Salvar programação" busy={busy} reset={false} onSubmit={values => { const date = new Date(stringValue(values, "startsAt")); if (Number.isNaN(date.getTime())) throw new Error("Informe uma data e um horário válidos."); return act({ action: "program.update", id: activity.id, title: stringValue(values, "title"), startsAt: date.toISOString() }); }}><CommunityField name="title" label="Atividade" maxLength={160} defaultValue={activity.title} /><CommunityField name="startsAt" label="Início (no fuso do seu dispositivo)" type="datetime-local" defaultValue={localDateTime(activity.startsAt)} /></CommunityForm></div></details>}{data.permissions.manage && <div className="mt-3 flex flex-wrap gap-2">{(["UPCOMING", "LIVE", "DONE"] as const).filter(status => status !== activity.status).map(status => <CommunityAction key={status} busy={busy} onClick={() => void act({ action: "program.status", id: activity.id, status })}>{states[status]}</CommunityAction>)}</div>}</li>)}</ol> : <CommunityEmpty>A programação será publicada pela organização.</CommunityEmpty>}
  </CommunityCard>;
}

export function CommunityQueues({ data, busy, act }: SectionProps) {
  const queueStates = { OPEN: "Inscrições abertas", PAUSED: "Inscrições pausadas", CLOSED: "Fila encerrada" };
  return <CommunityCard title="Espere sua vez sem perder o evento" description="Entre na fila da atividade. Quando chegar sua vez, acompanhe o aviso aqui e nas notificações.">
    {data.permissions.manage && <CommunityForm submit="Criar fila" busy={busy} onSubmit={values => act({ action: "queue.create", title: stringValue(values, "title") })}><CommunityField name="title" label="Nome da atividade ou atendimento" maxLength={160} /></CommunityForm>}
    {data.queues.length ? data.queues.map(queue => <article key={queue.id} className="space-y-3 rounded-xl border p-4">
      <div className="flex flex-wrap items-start justify-between gap-2"><h3 className="break-words font-semibold">{queue.title}</h3><CommunityBadge>{queueStates[queue.state]}</CommunityBadge></div>
      <p className="text-sm text-muted-foreground">{queue.waiting} pessoas aguardando</p>
      {queue.state !== "OPEN" && <p className="rounded-xl bg-muted/50 p-3 text-sm">{queue.state === "PAUSED" ? "Novas inscrições estão pausadas. A equipe pode continuar chamando quem já está na fila." : "Esta fila não aceita novas inscrições nem novas chamadas. As inscrições e posições ficam preservadas caso a equipe reabra. Consulte a organização para orientações."}</p>}
      {queue.mine && <p role="status" className="rounded-xl bg-primary/10 p-3 text-sm font-semibold text-primary">{queue.state === "CLOSED" && ["WAITING", "CALLED"].includes(queue.mine.status) ? "Fila encerrada. Sua inscrição foi preservada; consulte a organização para orientações." : queue.mine.status === "CALLED" ? "Chegou a sua vez! Procure a equipe da atividade." : queue.mine.status === "WAITING" ? `Sua posição na fila: ${queue.mine.position}` : queue.mine.status === "LEFT" ? "Você saiu desta fila." : "Seu atendimento foi concluído."}</p>}
      <div className="flex flex-wrap gap-2">
        {data.permissions.authenticated && (!queue.mine || !["WAITING", "CALLED"].includes(queue.mine.status)) && <CommunityAction busy={busy || queue.state !== "OPEN"} onClick={() => void act({ action: "queue.join", id: queue.id })}>Entrar na fila</CommunityAction>}
        {queue.mine && ["WAITING", "CALLED"].includes(queue.mine.status) && <CommunityAction busy={busy} onClick={() => void act({ action: "queue.leave", id: queue.id })}>Sair da fila</CommunityAction>}
        {data.permissions.team && <CommunityAction busy={busy || queue.state === "CLOSED"} onClick={() => void act({ action: "queue.next", id: queue.id })}>Chamar próxima pessoa</CommunityAction>}
      </div>
      {data.permissions.team && <div className="space-y-2 border-t pt-3"><p className="text-xs font-semibold text-muted-foreground">Controle da equipe</p><div className="flex flex-wrap gap-2">{(["OPEN", "PAUSED", "CLOSED"] as const).filter(state => state !== queue.state).map(state => <CommunityAction key={state} busy={busy} onClick={() => { if (state === "CLOSED" && !window.confirm("Encerrar esta fila? As pessoas aguardando continuarão registradas, mas não haverá novas chamadas.")) return; void act({ action: "queue.control", id: queue.id, state }); }}>{state === "OPEN" ? "Abrir inscrições" : state === "PAUSED" ? "Pausar inscrições" : "Encerrar fila"}</CommunityAction>)}</div></div>}
    </article>) : <CommunityEmpty>Nenhuma fila de atendimento aberta.</CommunityEmpty>}
  </CommunityCard>;
}
export function CommunityTeam({ data, busy, act, userId }: SectionProps) {
  return <div className="space-y-5"><CommunityCard title="Equipe do evento" description="Adicione colaboradores pela conta cadastrada para acompanhar tarefas. Acesso restrito à organização.">{data.permissions.manage && <CommunityForm submit="Adicionar colaborador" busy={busy} onSubmit={values => act({ action: "team.add", email: stringValue(values, "email") })}><CommunityField name="email" label="Email da conta" type="email" maxLength={254} /></CommunityForm>}{data.team.length ? <ul className="space-y-2">{data.team.map(member => <li key={member.userId} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-muted/40 p-3"><span className="break-words text-sm font-medium">{member.name}</span>{data.permissions.manage && <CommunityAction busy={busy} onClick={() => { if (window.confirm("Remover este colaborador da equipe?")) void act({ action: "team.remove", userId: member.userId }); }}>Remover</CommunityAction>}</li>)}</ul> : <CommunityEmpty>Nenhum colaborador adicionado.</CommunityEmpty>}</CommunityCard>
    <CommunityCard title="Tarefas e pedidos de ajuda" description="Atualize o andamento para que toda a equipe acompanhe o que precisa de atenção.">{data.permissions.manage && <CommunityForm submit="Criar tarefa" busy={busy} onSubmit={values => act({ action: "task.create", title: stringValue(values, "title"), assignedTo: stringValue(values, "assignedTo") === "unassigned" ? undefined : stringValue(values, "assignedTo") })}><CommunityField name="title" label="O que precisa ser feito?" maxLength={160} /><CommunitySelect name="assignedTo" label="Responsável" options={[{ value: "unassigned", label: "Sem responsável" }, ...data.team.map(member => ({ value: member.userId, label: member.name }))]} /></CommunityForm>}{data.tasks.length ? data.tasks.map(task => <article key={task.id} className="space-y-3 rounded-xl border p-4"><h3 className="break-words font-semibold">{task.title}</h3><div className="flex flex-wrap gap-2"><CommunityBadge>{states[task.status]}</CommunityBadge><span className="text-sm text-muted-foreground">{data.team.find(member => member.userId === task.assignedTo)?.name || "Sem responsável"}</span></div><div className="flex flex-wrap gap-2">{(data.permissions.manage || task.assignedTo === userId) && (["TODO", "HELP", "DONE"] as const).filter(status => status !== task.status).map(status => <CommunityAction key={status} busy={busy} onClick={() => void act({ action: "task.update", id: task.id, status })}>{states[status]}</CommunityAction>)}</div></article>) : <CommunityEmpty>As tarefas aparecerão aqui quando forem criadas.</CommunityEmpty>}</CommunityCard></div>;
}

export function CommunityLostFound({ data, busy, act }: SectionProps) {
  return <CommunityCard title="Achados e perdidos" description="Encontrou seu objeto? Envie uma descrição privada para a equipe verificar a devolução.">{data.permissions.team && <CommunityForm submit="Publicar objeto encontrado" busy={busy} onSubmit={values => act({ action: "lost.create", title: stringValue(values, "title"), description: stringValue(values, "description") })}><CommunityField name="title" label="Objeto" maxLength={160} /><CommunityField name="description" label="Descrição pública (guarde detalhes para confirmar o dono)" type="textarea" maxLength={1000} /></CommunityForm>}
    {data.lostItems.length ? data.lostItems.map(item => <article key={item.id} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="break-words font-semibold">{item.title}</h3>{item.returned && <CommunityBadge>Devolvido</CommunityBadge>}</div><p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{item.description}</p>{!item.returned && data.permissions.authenticated && !data.permissions.manage && <details className="rounded-xl bg-muted/40 p-3"><summary className="cursor-pointer text-sm font-semibold">Acredito que seja meu</summary><div className="mt-3"><CommunityForm submit="Enviar mensagem privada" busy={busy} onSubmit={values => act({ action: "lost.claim", id: item.id, message: stringValue(values, "message") })}><CommunityField name="message" label="Descreva detalhes que confirmem que o objeto é seu" type="textarea" maxLength={1000} /></CommunityForm></div></details>}{item.claims.length > 0 && <div className="space-y-2"><p className="text-xs font-semibold text-muted-foreground">Mensagens privadas · visíveis apenas para a equipe e o autor</p>{item.claims.map(claim => <div key={claim.id} className="space-y-2 rounded-xl bg-muted/50 p-3"><p className="whitespace-pre-wrap break-words text-sm">{claim.message}</p>{claim.resolved ? <CommunityBadge>Devolução confirmada</CommunityBadge> : data.permissions.team && !item.returned && <CommunityAction busy={busy} onClick={() => { if (window.confirm("Confirmar que este objeto foi devolvido ao autor desta mensagem?")) void act({ action: "lost.resolve", claimId: claim.id }); }}>Confirmar devolução</CommunityAction>}</div>)}</div>}</article>) : <CommunityEmpty>Nenhum objeto encontrado foi publicado.</CommunityEmpty>}
  </CommunityCard>;
}

export function CommunityFeedback({ data, busy, act }: SectionProps) {
  return <CommunityCard title="Como foi sua experiência?" description="Após o evento, compartilhe sua avaliação. Seus comentários ajudam o organizador a melhorar as próximas edições.">{data.permissions.team && <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-primary/5 p-4"><p className="text-xs font-semibold text-muted-foreground">Média das avaliações</p><p className="mt-2 text-3xl font-bold text-primary">{data.feedback.average === null ? "—" : data.feedback.average.toFixed(1)}<span className="ml-1 text-sm text-muted-foreground">/ 5</span></p></div><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs font-semibold text-muted-foreground">Respostas recebidas</p><p className="mt-2 text-3xl font-bold">{data.feedback.count}</p></div></div>}{data.feedback.eligible ? <CommunityForm submit={data.feedback.mine ? "Atualizar avaliação" : "Enviar avaliação"} busy={busy} reset={false} onSubmit={values => act({ action: "feedback.save", rating: Number(values.get("rating")), comment: stringValue(values, "comment") })}><CommunitySelect name="rating" label="Nota da experiência" defaultValue={String(data.feedback.mine?.rating ?? 5)} options={[5, 4, 3, 2, 1].map(value => ({ value: String(value), label: `${value} de 5` }))} /><CommunityField name="comment" label="Comentário privado para o organizador (opcional)" type="textarea" required={false} maxLength={1000} defaultValue={data.feedback.mine?.comment ?? ""} /></CommunityForm> : <CommunityEmpty>A avaliação fica disponível após o evento para as contas que confirmaram presença ou registraram entrada.</CommunityEmpty>}{data.permissions.manage && data.feedback.comments.length > 0 && <section className="space-y-3"><h3 className="font-semibold">Comentários recebidos · apenas organizador e administradores</h3>{data.feedback.comments.map((feedback, index) => <article key={index} className="rounded-xl border p-4"><CommunityBadge>{feedback.rating} de 5</CommunityBadge><p className="mt-2 whitespace-pre-wrap break-words text-sm">{feedback.comment || "Sem comentário."}</p></article>)}</section>}</CommunityCard>;
}
