"use client";

import Link from "next/link";
import { UsersRound } from "lucide-react";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { useCommunityRealtime } from "@/hooks/useCommunityRealtime";
import type { CommunityRoomSnapshot, CommunityRoomSummary } from "@/types/community";
import { useCommunityResource } from "./CommunityResource";
import { CommunityAction, CommunityBadge, CommunityCard, CommunityEmpty, CommunityField, CommunityForm, CommunitySelect, CommunitySyncStatus, CommunityInteractionBoundary, CommunityStaleBanner } from "./CommunityUI";

function CommunityRoomsHeader({ title, description }: { title: string; description: string }) {
  return <header className="flex items-start gap-3"><SidebarTrigger /><div className="min-w-0"><p className="flex items-center gap-2 text-sm font-semibold text-primary"><UsersRound className="size-4" aria-hidden="true" />Combine seu próximo evento</p><h1 className="mt-2 break-words text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div></header>;
}

export function CommunityRooms() {
  const resource = useCommunityResource<{ rooms: CommunityRoomSummary[] }>("/api/community/rooms");
  const realtime = useCommunityRealtime({ user: true }, resource.refresh);
  return <CommunityInteractionBoundary online={resource.online}><main className="w-full min-w-0 px-4 py-6 sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl space-y-6"><CommunityRoomsHeader title="Salas com amigos" description="Convide pessoas da sua turma, sugira eventos e decidam juntos. Cada sala é privada para seus membros." /><CommunitySyncStatus refreshing={resource.refreshing} error={resource.error} realtime={realtime} lastSuccessfulAt={resource.lastSuccessfulAt} /><CommunityStaleBanner error={resource.error} hasData={!!resource.data} online={resource.online} refreshing={resource.refreshing} refresh={() => void resource.refresh()} />
    {!resource.authenticated && !resource.loading ? <CommunityCard><p>Entre para criar uma sala ou acessar seus convites.</p><Link href="/login" className="font-semibold text-primary underline">Entrar</Link></CommunityCard> : <>
      <CommunityCard title="Criar uma sala" description="Depois de criar, convide seus amigos pelo email da conta deles."><CommunityForm submit="Criar sala privada" busy={resource.busy} onSubmit={values => resource.act({ action: "room.create", name: String(values.get("name") ?? "").trim() })}><CommunityField name="name" label="Nome da turma" maxLength={80} placeholder="Ex.: Amigos do fim de semana" /></CommunityForm></CommunityCard>
      {resource.loading ? <p role="status">Carregando suas salas...</p> : resource.error && !resource.data ? <CommunityCard><p role="alert">{resource.error}</p><CommunityAction busy={false} onClick={() => void resource.refresh()}>Tentar novamente</CommunityAction></CommunityCard> : <section aria-label="Suas salas" className="grid gap-4 sm:grid-cols-2">{resource.data?.rooms.length ? resource.data.rooms.map(room => <CommunityCard key={room.id} title={room.name}><div className="flex flex-wrap gap-2"><CommunityBadge>{room.members} membros</CommunityBadge><CommunityBadge>{room.suggestions} sugestões</CommunityBadge>{room.owner && <CommunityBadge>Você organiza</CommunityBadge>}</div><Link href={`/salas/${room.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">Abrir sala →</Link></CommunityCard>) : <CommunityEmpty>Nenhuma sala ainda. Crie a primeira ou peça a um amigo para adicionar o email da sua conta.</CommunityEmpty>}</section>}
    </>}{resource.message && <p role="status" className="rounded-xl border bg-muted/40 p-3 text-sm">{resource.message}</p>}</div></main></CommunityInteractionBoundary>;
}

export function CommunityRoom({ roomId }: { roomId: string }) {
  const resource = useCommunityResource<CommunityRoomSnapshot>(`/api/community/rooms/${encodeURIComponent(roomId)}`);
  const realtime = useCommunityRealtime({ roomId }, resource.refresh);
  const room = resource.data;
  return <CommunityInteractionBoundary online={resource.online}><main className="w-full min-w-0 px-4 py-6 sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl space-y-6"><CommunityRoomsHeader title={room?.name ?? "Sala com amigos"} description="As sugestões e os votos acompanham as mudanças da sua turma." /><CommunitySyncStatus refreshing={resource.refreshing} error={resource.error} realtime={realtime} lastSuccessfulAt={resource.lastSuccessfulAt} /><CommunityStaleBanner error={resource.error} hasData={!!resource.data} online={resource.online} refreshing={resource.refreshing} refresh={() => void resource.refresh()} /><Link href="/salas" className="inline-flex min-h-11 items-center text-sm font-semibold text-primary">← Todas as salas</Link>
    {resource.loading ? <p role="status">Carregando sala...</p> : resource.error && !resource.data ? <CommunityCard><p role="alert">{resource.error}</p><CommunityAction busy={false} onClick={() => void resource.refresh()}>Tentar novamente</CommunityAction></CommunityCard> : room && <>
      <CommunityCard title="Escolha uma experiência" description="Sugira um evento publicado e vote nas opções que combinam com a turma.">{room.availableEvents.length ? <CommunityForm submit="Sugerir evento" busy={resource.busy} onSubmit={values => resource.act({ action: "suggestion.add", eventId: values.get("eventId") })}><CommunitySelect name="eventId" label="Evento" options={room.availableEvents.map(event => ({ value: event.id, label: `${event.name} · ${event.date}` }))} /></CommunityForm> : <CommunityEmpty>Não há eventos publicados disponíveis para sugerir agora. <Link href="/EventsCreated" className="text-primary underline">Conferir a agenda</Link></CommunityEmpty>}
        <div className="space-y-3">{room.suggestions.length ? room.suggestions.map(suggestion => <article key={suggestion.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><Link href={`/eventos/${suggestion.event.id}`} className="break-words font-semibold text-primary hover:underline">{suggestion.event.name}</Link><p className="mt-1 text-sm text-muted-foreground">{suggestion.event.date} · sugerido por {suggestion.authorName || "Membro"}</p><p className="mt-2 text-sm font-medium">{suggestion.votes} votos</p></div><CommunityAction busy={resource.busy} onClick={() => void resource.act({ action: "suggestion.vote", suggestionId: suggestion.id, voted: !suggestion.mine })}>{suggestion.mine ? "Retirar meu voto" : "Quero ir"}</CommunityAction></div></article>) : <CommunityEmpty>Qual vai ser o próximo encontro? Adicione a primeira sugestão.</CommunityEmpty>}</div>
      </CommunityCard>
      <CommunityCard title="Pessoas nesta sala" description="Só os membros conseguem acessar as sugestões. Convites usam contas já cadastradas.">{room.owner && <CommunityForm submit="Adicionar amigo" busy={resource.busy} onSubmit={values => resource.act({ action: "member.add", email: String(values.get("email") ?? "").trim() })}><CommunityField name="email" label="Email da conta do amigo" type="email" maxLength={254} /></CommunityForm>}<ul className="space-y-2">{room.members.map(member => <li key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-muted/40 p-3"><span className="break-words text-sm font-medium">{member.name || "Membro"}{member.id === resource.userId ? " (você)" : ""}</span>{room.owner && member.id !== resource.userId && <CommunityAction busy={resource.busy} onClick={() => { if (window.confirm("Remover esta pessoa da sala?")) void resource.act({ action: "member.remove", userId: member.id }); }}>Remover</CommunityAction>}</li>)}</ul></CommunityCard>
    </>}{resource.message && <p role="status" className="rounded-xl border bg-muted/40 p-3 text-sm">{resource.message}</p>}</div></main></CommunityInteractionBoundary>;
}
