"use client";

import { useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { Heart, MessageCircle, Settings2, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { FadeInView } from "@/components/animations/FadeInView";
import { usePartyConnections } from "@/hooks/usePartyConnections";
import { usePartyRealtime } from "@/hooks/usePartyRealtime";
import { partyButton, PartyConfirm, PartySafetyActions } from "./PartyActions";
import PartyProfileForm, { partyIntents } from "./PartyProfileForm";
import PartyAvatar from "./PartyAvatar";
import type { PartyPublicProfile } from "@/types/partyConnections";

export default function PartyConnectionsHub({ eventId }: { eventId: string }) {
  const { data: session, status } = useSession();
  return <PartyConnectionsContent key={`${eventId}:${status}:${session?.user?.id ?? "guest"}:${session?.user?.role ?? ""}`} eventId={eventId} />;
}
function PartyConnectionsContent({ eventId }: { eventId: string }) {
  const resource = usePartyConnections(eventId);
  const realtime = usePartyRealtime({ partyEventId: eventId }, resource.refresh, resource.revoke, !!resource.data?.mine?.active && !!resource.data?.eligible);
  const [section, setSection] = useState<"discover" | "matches" | "preferences">("discover");
  const data = resource.data;
  const busy = resource.busy || !resource.online || resource.revoked;
  const profileCard = (profile: PartyPublicProfile) => <article key={profile.userId} className="overflow-hidden rounded-3xl border bg-card shadow-sm"><div className="relative grid aspect-[5/4] place-items-center overflow-hidden bg-gradient-to-br from-primary/20 via-primary/5 to-muted"><span className="grid size-full place-items-center text-6xl font-bold text-primary/70"><PartyAvatar key={profile.photoUrl} url={profile.photoUrl} name={profile.displayName} /></span><span className="absolute bottom-4 left-4 rounded-full border bg-background/95 px-3 py-1.5 text-xs font-semibold shadow-sm">{partyIntents[profile.intent].label}</span></div><div className="space-y-4 p-5"><h2 className="break-words text-xl font-semibold">{profile.displayName}</h2>{profile.bio && <p className="whitespace-pre-wrap break-words text-sm leading-6 text-muted-foreground">{profile.bio}</p>}<div className="flex flex-wrap gap-2">{profile.interests.map(interest => <span key={interest} className="rounded-full bg-muted px-3 py-1 text-xs">{interest}</span>)}</div><button type="button" disabled={busy || profile.liked} onClick={() => void resource.act({ action: "like", userId: profile.userId })} className={`${partyButton} w-full ${profile.liked ? "border bg-muted text-muted-foreground" : "bg-primary text-primary-foreground"}`}><Heart size={16} aria-hidden="true" />{profile.liked ? "Seu interesse está registrado" : "Quero conhecer"}</button><PartySafetyActions userId={profile.userId} displayName={profile.displayName} busy={busy} act={resource.act} /></div></article>;
  return <main className="w-full min-w-0 px-4 py-6 sm:px-6 lg:px-10"><div className="mx-auto max-w-6xl space-y-6"><FadeInView><header className="flex items-start gap-3"><SidebarTrigger /><div className="min-w-0 flex-1"><Link href={`/eventos/${encodeURIComponent(eventId)}`} className="inline-flex min-h-9 items-center text-sm text-muted-foreground hover:text-primary">← Voltar ao evento</Link><p className="mt-3 text-xs font-bold uppercase tracking-[.2em] text-primary">Conexões da festa</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">A melhor parte pode ser quem você encontra.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{data?.event.name ?? "Seu evento"} · Descubra pessoas com interesses em comum, sem pressa e com privacidade.</p></div></header></FadeInView><section className="flex flex-wrap items-center justify-between gap-5 rounded-3xl border border-primary/15 bg-gradient-to-br from-primary/10 via-card to-card p-5 sm:p-7"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-primary text-primary-foreground"><Sparkles aria-hidden="true" /></span><div><h2 className="font-semibold">O interesse precisa ser dos dois.</h2><p className="mt-1 max-w-xl text-sm leading-6 text-muted-foreground">Sua curtida é privada. A conversa só abre quando vocês se curtem. Não mostramos rejeições nem curtidas recebidas sem correspondência.</p></div></div><span className="inline-flex items-center gap-2 rounded-full border bg-background px-3 py-2 text-xs font-medium"><ShieldCheck size={14} className="text-primary" aria-hidden="true" />Participação opcional</span></section>
    <div className="flex flex-wrap items-center justify-between gap-3"><nav aria-label="Seções das conexões" className="flex max-w-full flex-wrap gap-1 rounded-2xl border bg-card p-1">{([{ id: "discover", label: "Descobrir", icon: UsersRound }, { id: "matches", label: "Conexões", icon: Heart }, { id: "preferences", label: "Meu perfil", icon: Settings2 }] as const).map(item => <button type="button" key={item.id} onClick={() => setSection(item.id)} aria-current={section === item.id ? "page" : undefined} className={`${partyButton} ${section === item.id ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}><item.icon size={16} aria-hidden="true" />{item.label}{item.id === "matches" && !!data?.matches.length && <span className="rounded-full bg-foreground/10 px-2 py-0.5 text-xs">{data.matches.length}</span>}</button>)}</nav><button type="button" className={`${partyButton} border`} disabled={!resource.online || resource.refreshing} onClick={() => void resource.refresh()}>Atualizar</button></div>
    <div aria-live="polite" className="space-y-2">{resource.error && <p role="alert" className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm">{resource.error}</p>}{resource.message && <p role="status" className="rounded-xl border bg-muted/30 p-4 text-sm">{resource.message}</p>}{!resource.online && <p className="rounded-xl border p-4 text-sm text-muted-foreground">Sem conexão. Você pode editar seu perfil; curtidas e alterações serão liberadas ao reconectar.</p>}{resource.revoked && <p className="rounded-xl border p-4 text-sm">Seu acesso mudou. Estamos conferindo sua participação antes de mostrar outras pessoas.</p>}</div>
    {resource.loading ? <p role="status" className="rounded-3xl border p-8 text-center text-sm text-muted-foreground">Preparando suas conexões…</p> : data && <>{!data.eligible && <div className="rounded-3xl border p-6"><h2 className="text-xl font-semibold">Confirme sua presença primeiro</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A descoberta é exclusiva para participantes confirmados ou com check-in. Organizar ou administrar o evento não substitui essa participação.</p><Link href={`/eventos/${encodeURIComponent(eventId)}`} className={`${partyButton} mt-4 bg-primary text-primary-foreground`}>Ver minha inscrição</Link></div>}
    {(section === "preferences" || !data.mine?.active && data.eligible) && <><PartyProfileForm key={data.mine?.active ? "active" : "inactive"} profile={data.mine} eligible={data.eligible && resource.online && !resource.revoked} busy={resource.busy} act={resource.act} />{data.mine?.active && <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border p-5"><div><h3 className="font-semibold">Você está na descoberta</h3><p className="mt-1 text-sm text-muted-foreground">Sair remove seu perfil da descoberta e encerra o acesso às conversas correspondentes.</p></div><PartyConfirm title="Sair das conexões deste evento?" description="Seu perfil deixa de aparecer, e os acessos às conversas são revogados. Para participar novamente, salve seu perfil; novos interesses mútuos podem ser necessários." label="Sair da descoberta" destructive busy={busy} onConfirm={() => resource.act({ action: "profile.leave" })} /></div>}{data.blocks.length > 0 && <section className="rounded-3xl border bg-card p-5"><h2 className="text-lg font-semibold">Contas bloqueadas</h2><ul className="mt-4 divide-y">{data.blocks.map(block => <li key={block.userId} className="flex flex-wrap items-center justify-between gap-3 py-3"><span className="break-words text-sm">{block.displayName}</span><PartyConfirm title="Remover este bloqueio?" description="Essa pessoa pode voltar a aparecer na descoberta. Remover o bloqueio não abre automaticamente uma conversa." label="Desbloquear" busy={busy} onConfirm={() => resource.act({ action: "unblock", userId: block.userId })} /></li>)}</ul></section>}</>}
    {data.eligible && data.mine?.active && section === "discover" && <><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.profiles.map(profileCard)}</div>{data.profiles.length === 0 && <PartyEmpty title="Sua turma está chegando" text="Ainda não há outros perfis disponíveis nesta página. Volte depois ou explore as conversas do evento." />}<div className="flex justify-between gap-3"><button type="button" disabled={!resource.hasPrevious || resource.loading} onClick={resource.previous} className={`${partyButton} border`}>← Anteriores</button><button type="button" disabled={!data.nextAfter || resource.loading} onClick={resource.next} className={`${partyButton} border`}>Próximos →</button></div></>}
    {data.eligible && data.mine?.active && section === "matches" && <>{data.matches.length === 0 ? <PartyEmpty title="Boas conexões levam um instante" text="Quando o interesse for mútuo, vocês aparecem aqui e podem começar uma conversa privada." /> : <div className="grid gap-4 sm:grid-cols-2">{data.matches.map(match => <article key={match.id} className="rounded-3xl border bg-card p-5"><div className="flex items-center gap-3"><span className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-2xl bg-primary/10 text-xl font-bold text-primary"><PartyAvatar key={match.profile.photoUrl} url={match.profile.photoUrl} name={match.profile.displayName} decorative /></span><div className="min-w-0"><h2 className="break-words text-lg font-semibold">{match.profile.displayName}</h2><p className="text-xs text-muted-foreground">Vocês querem se conhecer</p></div><Heart size={18} className="ml-auto shrink-0 text-primary" aria-hidden="true" /></div><Link href={`/eventos/${encodeURIComponent(eventId)}/conexoes/${encodeURIComponent(match.id)}`} className={`${partyButton} mt-5 w-full bg-primary text-primary-foreground`}><MessageCircle size={16} aria-hidden="true" />Abrir conversa privada</Link><div className="mt-3"><PartySafetyActions userId={match.profile.userId} displayName={match.profile.displayName} busy={busy} act={resource.act} /></div></article>)}</div>}</>}
    </>}<footer className="flex flex-wrap items-center justify-between gap-3 border-t pt-5 text-xs leading-5 text-muted-foreground"><p>Sem localização exata. Sem exposição de contatos. Você controla sua participação.</p><span>{realtime === "live" ? "Conexões atualizadas em tempo real" : "Atualização segura pelo servidor"}</span></footer>
  </div></main>;
}
function PartyEmpty({ title, text }: { title: string; text: string }) { return <div className="grid min-h-56 place-content-center gap-3 rounded-3xl border border-dashed p-8 text-center"><Heart className="mx-auto size-8 text-primary" aria-hidden="true" /><h2 className="text-xl font-semibold">{title}</h2><p className="max-w-md text-sm leading-6 text-muted-foreground">{text}</p></div>; }
