"use client";
import { useState } from "react";
import { Evento } from "@/types";
export type DiscoveryFilter = { category: string; free: boolean; maxPrice: string; radius: string; origin: {lat:number;lng:number} | null };
export const emptyDiscoveryFilter: DiscoveryFilter = {category:'',free:false,maxPrice:'',radius:'',origin:null};
export function filterDiscovery(events: Evento[], filter: DiscoveryFilter) {
 return events.filter(event => { if(filter.category && event.category!==filter.category)return false;if(filter.free && !event.isFree)return false;if(filter.maxPrice && !event.isFree && (event.priceCents==null || event.priceCents<=0 || event.priceCents>Number(filter.maxPrice)*100))return false;if(filter.radius && filter.origin){if(event.lat==null || event.lng==null)return false;const rad=(value:number)=>value*Math.PI/180;const dlat=rad(event.lat-filter.origin.lat),dlng=rad(event.lng-filter.origin.lng);const a=Math.sin(dlat/2)**2+Math.cos(rad(filter.origin.lat))*Math.cos(rad(event.lat))*Math.sin(dlng/2)**2;const distance=6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));if(distance>Number(filter.radius))return false;}return true; });
}
export default function PublicEventFilters({ events, value, onChange }: {events:Evento[];value:DiscoveryFilter;onChange:(value:DiscoveryFilter)=>void}) {
 const [locationMessage, setLocationMessage] = useState('');
 const categories=Array.from(new Set(events.map(event=>event.category).filter((category):category is NonNullable<Evento['category']> => Boolean(category))));
 const input='min-h-11 rounded-xl border bg-background px-3 text-sm';
 return <details className="rounded-2xl border bg-card p-4"><summary className="cursor-pointer text-sm font-semibold">Mais filtros · categoria, preço e distância</summary><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-2 text-sm">Categoria<select className={input} value={value.category} onChange={e=>onChange({...value,category:e.target.value})}><option value="">Todas</option>{categories.map(category=><option key={category} value={category}>{category}</option>)}</select></label><label className="grid gap-2 text-sm">Preço máximo (R$)<input className={input} type="number" min="0" value={value.maxPrice} placeholder="Sem limite" onChange={e=>onChange({...value,maxPrice:e.target.value})}/></label><label className="flex min-h-11 items-center gap-2 self-end text-sm"><input type="checkbox" checked={value.free} onChange={e=>onChange({...value,free:e.target.checked})}/>Somente gratuitos</label><div className="space-y-2"><label className="grid gap-2 text-sm">Perto de mim<select className={input} value={value.radius} onChange={e=>{const radius=e.target.value;if(!radius){onChange({...value,radius:''});return;}if(value.origin){onChange({...value,radius});return;}if(!navigator.geolocation){setLocationMessage('Este navegador não oferece localização. Use os outros filtros.');onChange({...value,radius:''});return;}setLocationMessage('Obtendo localização...');navigator.geolocation.getCurrentPosition(position=>{setLocationMessage('Localização aplicada ao filtro.');onChange({...value,radius,origin:{lat:position.coords.latitude,lng:position.coords.longitude}});},()=>{onChange({...value,radius:''});setLocationMessage('Não foi possível obter a localização. Permita o acesso no navegador ou use os outros filtros.');},{timeout:10000,maximumAge:60000});}}><option value="">Qualquer distância</option><option value="5">Até 5 km</option><option value="10">Até 10 km</option><option value="25">Até 25 km</option><option value="50">Até 50 km</option></select></label><p className="text-xs text-muted-foreground">Localização solicitada apenas ao escolher uma distância. Eventos sem coordenadas ficam fora deste filtro.</p></div></div><p role="status" className="mt-3 text-sm text-muted-foreground">{locationMessage}</p><button className="mt-4 text-sm font-semibold text-primary underline" type="button" onClick={()=>onChange(emptyDiscoveryFilter)}>Limpar filtros</button></details>;
}
