"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { useSocket } from "@/context/SocketContext";
import { getNotifications, markNotificationRead } from "@/app/(actions)/engagement/action";
import { NotificationDTO } from "@/types/features";
import PushSettings from "@/components/MyComponents/PushSettings";
import { SidebarTrigger } from "@/components/ui/sidebar";
export default function Notifications(){const {data:session,status}=useSession();const socket=useSocket();const identity=useRef(session?.user?.id);identity.current=session?.user?.id;const [items,setItems]=useState<NotificationDTO[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [unread,setUnread]=useState(false);
 const refresh=useCallback(async()=>{try{const requestedIdentity=identity.current;const result=await getNotifications();if(requestedIdentity!==identity.current)return;setItems(result);setError('');}catch{setError('Não foi possível carregar os avisos.');}finally{setLoading(false);}},[]);
 useEffect(()=>{if(status==='loading')return;if(status!=='authenticated'){setItems([]);setLoading(false);return;}setItems([]);setLoading(true);void refresh();const update=()=>void refresh();socket.on('notification-updated',update);socket.on('connect',update);return()=>{socket.off('notification-updated',update);socket.off('connect',update);};},[refresh,socket,status,session?.user?.id]);
 async function mark(id:string|null){setBusy(true);try{const result=await markNotificationRead(id);if(!result.success)throw new Error();await refresh();window.dispatchEvent(new Event('eventmap-notifications-read'));}catch{setError('Não foi possível marcar o aviso. Tente novamente.');}finally{setBusy(false);}}
 const visible=unread?items.filter(item=>!item.readAt):items;
 return <main className="w-full px-4 py-6 sm:px-6 lg:px-10"><div className="mx-auto max-w-3xl space-y-6"><header className="flex gap-4"><SidebarTrigger/><div><h1 className="text-3xl font-bold">Notificações</h1><p className="mt-2 text-muted-foreground">Mudanças dos seus eventos, novidades e lembretes.</p></div></header>{status!=='authenticated'&&status!=='loading'?<Link href="/login" className="text-primary underline">Entre para ver suas notificações</Link>:<><PushSettings/><div className="flex flex-wrap justify-between gap-3"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={unread} onChange={e=>setUnread(e.target.checked)}/>Somente não lidas</label><button type="button" disabled={busy||!items.some(item=>!item.readAt)} onClick={()=>void mark(null)} className="min-h-11 rounded-xl border px-4 text-sm font-semibold">Marcar todas como lidas</button></div>{error&&<div role="alert" className="rounded-xl border p-4"><p>{error}</p><button className="mt-2 text-primary underline" onClick={()=>void refresh()}>Tentar novamente</button></div>}{loading?<p role="status">Carregando notificações...</p>:visible.length===0?<p className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">{unread?'Você está em dia. Nenhum aviso não lido.':'Os próximos avisos aparecerão aqui.'}</p>:<ol className="space-y-3">{visible.map(item=><li key={item.id} className={'rounded-2xl border bg-card p-5 '+(!item.readAt?'border-primary/40':'')}><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{!item.readAt&&<span className="mr-2 text-primary" aria-label="Não lida">●</span>}{item.title}</h2><time dateTime={item.createdAt} className="shrink-0 text-xs text-muted-foreground">{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.createdAt))}</time></div><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.message}</p><div className="mt-4 flex flex-wrap gap-4">{item.href.startsWith('/')&&!item.href.startsWith('//')&&<Link href={item.href} onClick={()=>{if(!item.readAt)void mark(item.id);}} className="text-sm font-semibold text-primary">Ver detalhes →</Link>}{!item.readAt&&<button type="button" disabled={busy} onClick={()=>void mark(item.id)} className="text-sm underline">Marcar como lida</button>}</div></li>)}</ol>}</>}</div></main>;
}
